### ISSUE TITLE
The token describing the number

### ISSUE THREAD

**Issue by MiniGerkules** [MiniGerkules/JerLang#1]
# The token describing the number
Write a class describing a token number. In the class, be sure to override the toString method. it should return the class name as a String. Also, the class must inherit from the [TokenType](https://github.com/MiniGerkules/JerLang/blob/master/src/main/kotlin/tokens/TokenType.kt) class. In the constructor of the TokenType class, the new class must pass a regular expression that specifies the type of token \<number\>.

**Comment by praymontana** [comment]
Cool
I can't do that
